name: kioku_navi
description: "Kioku Navi"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  getwidget: ^6.0.0
  form_builder_validators: ^11.1.2
  flutter_gen_runner: ^5.10.0
  animated_custom_dropdown: ^3.1.1
  dio: ^5.8.0+1
  get_storage: ^2.1.1
  calendar_date_picker2: ^2.0.1
  flutter_inner_shadow: ^0.0.1
  bubble: ^1.2.1
  splash_master: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter_gen:
  output: lib/generated/

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/locales/
